In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2])
v2 = np.array([3,4])

result = 2*v1+3*v2

print(result)

[11 16]


In [3]:
v1 = np.array([1,2])
v2 = np.array([2,5])
v3 = np.array([4,1])

result = 2*v1+3*v2-v3

print(result)

[ 4 18]


In [4]:
v1 = np.array([1,2])
v2 = np.array([4,1])
v3 = np.array([2,3])

a, b, c =4, -2, 5

result = a*v1+b*v2+c*v3

print(result)

[ 6 21]


In [5]:
v1 = np.random.randint(1, 10, 3)
v2 = np.random.randint(1, 10, 3)

print(v1)
print(v2)
print(3*v1+2*v2)

[6 4 1]
[1 8 7]
[20 28 17]


In [ ]:
x=np.array([25,4,1])
w=np.array([0.5,3.2,7])

prediction = np.dot(x,w)

prediction

np.float64(32.3)

In [8]:
v = np.array([2,1])

for a in [-3,-2-1,0,1,2,3]:
    print(a*v)


[-6 -3]
[-6 -3]
[0 0]
[2 1]
[4 2]
[6 3]


In [9]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])
v3 = np.array([0,0,1])


point = 2*v1+5*v2+8*v3

print(point)

[2 5 8]


In [10]:
a = np.array([
    [1,0],
    [0,1]
])


print(np.linalg.matrix_rank(a))

2
