# Matritsa va NumPy Array
Bu notebook NumPy array va matritsalar bilan ishlashning asosiy amallarini izohlaydi.

## NumPy import
Ushbu bo'lim **NumPy import** amali qanday ishlashini ko'rsatadi.

In [2]:
import numpy as np

## 1D Array
Ushbu bo'lim **1D Array** amali qanday ishlashini ko'rsatadi.

In [3]:
arr=np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


## 2D Array (Matritsa)
Ushbu bo'lim **2D Array (Matritsa)** amali qanday ishlashini ko'rsatadi.

In [4]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Shape, ndim, size
Ushbu bo'lim **Shape, ndim, size** amali qanday ishlashini ko'rsatadi.

In [5]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)

(3, 3)
2
9


## Indekslash
Ushbu bo'lim **Indekslash** amali qanday ishlashini ko'rsatadi.

In [6]:
print(matrix[0,1])
print(matrix[:,1])

2
[2 5 8]


## Nol va birlik matritsa
Ushbu bo'lim **Nol va birlik matritsa** amali qanday ishlashini ko'rsatadi.

In [7]:
print(np.zeros((3,3)))
print(np.ones((2,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Arifmetik amallar
Ushbu bo'lim **Arifmetik amallar** amali qanday ishlashini ko'rsatadi.

In [8]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)
print(A*B)
print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


## Transpose
Ushbu bo'lim **Transpose** amali qanday ishlashini ko'rsatadi.

In [9]:
print(A.T)

[[1 3]
 [2 4]]


## Statistik funksiyalar
Ushbu bo'lim **Statistik funksiyalar** amali qanday ishlashini ko'rsatadi.

In [10]:
x=np.array([10,20,30,40])
print(x.sum(),x.mean(),x.max(),x.min())

100 25.0 40 10


## Reshape
Ushbu bo'lim **Reshape** amali qanday ishlashini ko'rsatadi.

In [11]:
a=np.arange(1,7)
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


## Boolean indexing
Ushbu bo'lim **Boolean indexing** amali qanday ishlashini ko'rsatadi.

In [12]:
a=np.array([10,20,30,40,50])
print(a[a>25])

[30 40 50]


## Linear algebra
Ushbu bo'lim **Linear algebra** amali qanday ishlashini ko'rsatadi.

In [13]:
M=np.array([[2,1],[5,3]])
print(np.linalg.det(M))
print(np.linalg.inv(M))

1.0000000000000009
[[ 3. -1.]
 [-5.  2.]]
