# Vektor elementlariga murojat

In [2]:
import numpy as np

v = np.array([5,10,15,20])

print(v[0])
print(v[2])


5
15


# Vektor uzunligi

In [4]:
v = np.array([1,2,3,4,5])

print(len(v))

5


# Vektorlarni qo'shish

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

[5 7 9]


# Vektorlarni ayirish

In [8]:
a = np.array([10,20,30])
b = np.array([2,5,10])

print(a-b)

[ 8 15 20]


# Vektorlarni songa ko'paytirish

In [9]:
v = np.array([2,4,6])

print(v*3)

[ 6 12 18]


# Vektroni songa bo'lish

In [10]:
v = np.array([10,20,30])

print(v/10)


[1. 2. 3.]


# Numpyda matritsa yaratish

In [11]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a.shape)

(3, 3)


In [12]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(a.shape)

(3, 2)


# Matritsalarni qo'shish

In [13]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a+b)

[[ 6  8]
 [10 12]]


# Matritsalarni ayirish

In [14]:
a = np.array([
    [8,6],
    [4,2]
])

b = np.array([
    [1,2],
    [3,4]
])

print(a-b)

[[ 7  4]
 [ 1 -2]]


# matritsalarni ko'paytirish

In [15]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a*5)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


# Matritsalarni ko'paytirish

ko'paytirganda bir xil indeksdagi elementlar ko'payadi

In [16]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a*b)

[[ 5 12]
 [21 32]]


# ML'da Matrix multiplatication

In [17]:
a = np.array([
    [1,2],
    [3,4]
])

b = np.array([
    [5,6],
    [7,8]
])

print(a@b)

[[19 22]
 [43 50]]


# Transpose

In [18]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


# Identity matrix

In [19]:
i = np.eye(3)

print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 0 Matritsa

In [23]:
print(np.zeros([2,3]))

[[0. 0. 0.]
 [0. 0. 0.]]
